In [1]:
%pip install pandas numpy matplotlib seaborn scikit-learn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Cargar el dataset
df = pd.read_csv('OnlineNewsPopularity.csv')

# 2. Limpiar espacios en blanco en los nombres de las columnas
df.columns = [col.strip() for col in df.columns]

# 3. Eliminar columnas no predictivas
df_clean = df.drop(['url', 'timedelta'], axis=1)

print(f"Dataset cargado con éxito.")
print(f"Filas: {df_clean.shape[0]} | Columnas: {df_clean.shape[1]}")

Requirement already satisfied: pandas in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (2.4.4)
Requirement already satisfied: matplotlib in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (3.10.9)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: scikit-learn in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\Users\santy\Documents\SANTIAGO\UNIVERSIDAD\8TO SEMESTRE\Mineria\Online-News-Popularity\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.
Dataset cargado con éxito.
Filas: 39644 | Columnas: 59

In [2]:
# 4. Revisar información general
print(df_clean.info())

# 5. Revisar valores faltantes
print("\nValores faltantes por columna:")
print(df_clean.isnull().sum().sort_values(ascending=False))

# 6. Revisar duplicados
print("\nFilas duplicadas:", df_clean.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 39644 entries, 0 to 39643
Data columns (total 59 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   n_tokens_title                 39644 non-null  float64
 1   n_tokens_content               39644 non-null  float64
 2   n_unique_tokens                39644 non-null  float64
 3   n_non_stop_words               39644 non-null  float64
 4   n_non_stop_unique_tokens       39644 non-null  float64
 5   num_hrefs                      39644 non-null  float64
 6   num_self_hrefs                 39644 non-null  float64
 7   num_imgs                       39644 non-null  float64
 8   num_videos                     39644 non-null  float64
 9   average_token_length           39644 non-null  float64
 10  num_keywords                   39644 non-null  float64
 11  data_channel_is_lifestyle      39644 non-null  float64
 12  data_channel_is_entertainment  39644 non-null  float64
 13  data_channel_is_bus            39644 non-null  float64
 14  data_channel_is_socmed         39644 non-null  float64
 15  data_channel_is_tech           39644 non-null  float64
 16  data_channel_is_world          39644 non-null  float64
 17  kw_min_min                     39644 non-null  float64
 18  kw_max_min                     39644 non-null  float64
 19  kw_avg_min                     39644 non-null  float64
 20  kw_min_max                     39644 non-null  float64
 21  kw_max_max                     39644 non-null  float64
 22  kw_avg_max                     39644 non-null  float64
 23  kw_min_avg                     39644 non-null  float64
 24  kw_max_avg                     39644 non-null  float64
 25  kw_avg_avg                     39644 non-null  float64
 26  self_reference_min_shares      39644 non-null  float64
 27  self_reference_max_shares      39644 non-null  float64
 28  self_reference_avg_sharess     39644 non-null  float64
 29  weekday_is_monday              39644 non-null  float64
 30  weekday_is_tuesday             39644 non-null  float64
 31  weekday_is_wednesday           39644 non-null  float64
 32  weekday_is_thursday            39644 non-null  float64
 33  weekday_is_friday              39644 non-null  float64
 34  weekday_is_saturday            39644 non-null  float64
 35  weekday_is_sunday              39644 non-null  float64
 36  is_weekend                     39644 non-null  float64
 37  LDA_00                         39644 non-null  float64
 38  LDA_01                         39644 non-null  float64
 39  LDA_02                         39644 non-null  float64
 40  LDA_03                         39644 non-null  float64
 41  LDA_04                         39644 non-null  float64
 42  global_subjectivity            39644 non-null  float64
 43  global_sentiment_polarity      39644 non-null  float64
 44  global_rate_positive_words     39644 non-null  float64
 45  global_rate_negative_words     39644 non-null  float64
 46  rate_positive_words            39644 non-null  float64
 47  rate_negative_words            39644 non-null  float64
 48  avg_positive_polarity          39644 non-null  float64
 49  min_positive_polarity          39644 non-null  float64
 50  max_positive_polarity          39644 non-null  float64
 51  avg_negative_polarity          39644 non-null  float64
 52  min_negative_polarity          39644 non-null  float64
 53  max_negative_polarity          39644 non-null  float64
 54  title_subjectivity             39644 non-null  float64
 55  title_sentiment_polarity       39644 non-null  float64
 56  abs_title_subjectivity         39644 non-null  float64
 57  abs_title_sentiment_polarity   39644 non-null  float64
 58  shares                         39644 non-null  int64
dtypes: float64(58), int64(1)
memory usage: 17.8 MB
None

Valores faltantes por columna:
n_tokens_title                   0
n_tokens_content                 0
n_unique_tokens                  0
n_non_stop_words                 0
n_non_stop_unique_tokens         0
num_hrefs                        0
num_self_hrefs                   0
num_imgs                         0
num_videos                       0
average_token_length             0
num_keywords                     0
data_channel_is_lifestyle        0
data_channel_is_entertainment    0
data_channel_is_bus              0
data_channel_is_socmed           0
data_channel_is_tech             0
data_channel_is_world            0
kw_min_min                       0
kw_max_min                       0
kw_avg_min                       0
kw_min_max                       0
kw_max_max                       0
kw_avg_max                       0
kw_min_avg                       0
kw_max_avg                       0
kw_avg_avg                       0
self_reference_min_shares        0
self_reference_max_shares        0
self_reference_avg_sharess       0
weekday_is_monday                0
weekday_is_tuesday               0
weekday_is_wednesday             0
weekday_is_thursday              0
weekday_is_friday                0
weekday_is_saturday              0
weekday_is_sunday                0
is_weekend                       0
LDA_00                           0
LDA_01                           0
LDA_02                           0
LDA_03                           0
LDA_04                           0
global_subjectivity              0
global_sentiment_polarity        0
global_rate_positive_words       0
global_rate_negative_words       0
rate_positive_words              0
rate_negative_words              0
avg_positive_polarity            0
min_positive_polarity            0
max_positive_polarity            0
avg_negative_polarity            0
min_negative_polarity            0
max_negative_polarity            0
title_subjectivity               0
title_sentiment_polarity         0
abs_title_subjectivity           0
abs_title_sentiment_polarity     0
shares                           0
dtype: int64

Filas duplicadas: 0

In [3]:
# 7. Estadísticas descriptivas
df_clean.describe().T

,count,mean,std,min,25%,50%,75%,max
n_tokens_title,39644.0,10.398749,2.114037,2.00000,9.000000,10.000000,12.000000,23.000000
n_tokens_content,39644.0,546.514731,471.107508,0.00000,246.000000,409.000000,716.000000,8474.000000
n_unique_tokens,39644.0,0.548216,3.520708,0.00000,0.470870,0.539226,0.608696,701.000000
n_non_stop_words,39644.0,0.996469,5.231231,0.00000,1.000000,1.000000,1.000000,1042.000000
n_non_stop_unique_tokens,39644.0,0.689175,3.264816,0.00000,0.625739,0.690476,0.754630,650.000000
num_hrefs,39644.0,10.883690,11.332017,0.00000,4.000000,8.000000,14.000000,304.000000
num_self_hrefs,39644.0,3.293638,3.855141,0.00000,1.000000,3.000000,4.000000,116.000000
num_imgs,39644.0,4.544143,8.309434,0.00000,1.000000,1.000000,4.000000,128.000000
num_videos,39644.0,1.249874,4.107855,0.00000,0.000000,0.000000,1.000000,91.000000
average_token_length,39644.0,4.548239,0.844406,0.00000,4.478404,4.664082,4.854839,8.041534
num_keywords,39644.0,7.223767,1.909130,1.00000,6.000000,7.000000,9.000000,10.000000
data_channel_is_lifestyle,39644.0,0.052946,0.223929,0.00000,0.000000,0.000000,0.000000,1.000000
data_channel_is_entertainment,39644.0,0.178009,0.382525,0.00000,0.000000,0.000000,0.000000,1.000000
data_channel_is_bus,39644.0,0.157855,0.364610,0.00000,0.000000,0.000000,0.000000,1.000000
data_channel_is_socmed,39644.0,0.058597,0.234871,0.00000,0.000000,0.000000,0.000000,1.000000
data_channel_is_tech,39644.0,0.185299,0.388545,0.00000,0.000000,0.000000,0.000000,1.000000
data_channel_is_world,39644.0,0.212567,0.409129,0.00000,0.000000,0.000000,0.000000,1.000000
kw_min_min,39644.0,26.106801,69.633215,-1.00000,-1.000000,-1.000000,4.000000,377.000000
kw_max_min,39644.0,1153.951682,3857.990877,0.00000,445.000000,660.000000,1000.000000,298400.000000
kw_avg_min,39644.0,312.366967,620.783887,-1.00000,141.750000,235.500000,357.000000,42827.857143
kw_min_max,39644.0,13612.354102,57986.029357,0.00000,0.000000,1400.000000,7900.000000,843300.000000
kw_max_max,39644.0,752324.066694,214502.129573,0.00000,843300.000000,843300.000000,843300.000000,843300.000000
kw_avg_max,39644.0,259281.938083,135102.247285,0.00000,172846.875000,244572.222223,330980.000000,843300.000000
kw_min_avg,39644.0,1117.146610,1137.456951,-1.00000,0.000000,1023.635611,2056.781032,3613.039819
kw_max_avg,39644.0,5657.211151,6098.871957,0.00000,3562.101631,4355.688836,6019.953968,298400.000000
kw_avg_avg,39644.0,3135.858639,1318.150397,0.00000,2382.448566,2870.074878,3600.229564,43567.659946
self_reference_min_shares,39644.0,3998.755396,19738.670516,0.00000,639.000000,1200.000000,2600.000000,843300.000000
self_reference_max_shares,39644.0,10329.212662,41027.576613,0.00000,1100.000000,2800.000000,8000.000000,843300.000000
self_reference_avg_sharess,39644.0,6401.697580,24211.332231,0.00000,981.187500,2200.000000,5200.000000,843300.000000
weekday_is_monday,39644.0,0.168020,0.373889,0.00000,0.000000,0.000000,0.000000,1.000000
weekday_is_tuesday,39644.0,0.186409,0.389441,0.00000,0.000000,0.000000,0.000000,1.000000
weekday_is_wednesday,39644.0,0.187544,0.390353,0.00000,0.000000,0.000000,0.000000,1.000000
weekday_is_thursday,39644.0,0.183306,0.386922,0.00000,0.000000,0.000000,0.000000,1.000000
weekday_is_friday,39644.0,0.143805,0.350896,0.00000,0.000000,0.000000,0.000000,1.000000
weekday_is_saturday,39644.0,0.061876,0.240933,0.00000,0.000000,0.000000,0.000000,1.000000
weekday_is_sunday,39644.0,0.069039,0.253524,0.00000,0.000000,0.000000,0.000000,1.000000
is_weekend,39644.0,0.130915,0.337312,0.00000,0.000000,0.000000,0.000000,1.000000
LDA_00,39644.0,0.184599,0.262975,0.00000,0.025051,0.033387,0.240958,0.926994
LDA_01,39644.0,0.141256,0.219707,0.00000,0.025012,0.033345,0.150831,0.925947
LDA_02,39644.0,0.216321,0.282145,0.00000,0.028571,0.040004,0.334218,0.919999
LDA_03,39644.0,0.223770,0.295191,0.00000,0.028571,0.040001,0.375763,0.926534
LDA_04,39644.0,0.234029,0.289183,0.00000,0.028574,0.040727,0.399986,0.927191
global_subjectivity,39644.0,0.443370,0.116685,0.00000,0.396167,0.453457,0.508333,1.000000
global_sentiment_polarity,39644.0,0.119309,0.096931,-0.39375,0.057757,0.119117,0.177832,0.727841
global_rate_positive_words,39644.0,0.039625,0.017429,0.00000,0.028384,0.039023,0.050279,0.155488
global_rate_negative_words,39644.0,0.016612,0.010828,0.00000,0.009615,0.015337,0.021739,0.184932
rate_positive_words,39644.0,0.682150,0.190206,0.00000,0.600000,0.710526,0.800000,1.000000
rate_negative_words,39644.0,0.287934,0.156156,0.00000,0.185185,0.280000,0.384615,1.000000
avg_positive_polarity,39644.0,0.353825,0.104542,0.00000,0.306244,0.358755,0.411428,1.000000
min_positive_polarity,39644.0,0.095446,0.071315,0.00000,0.050000,0.100000,0.100000,1.000000
max_positive_polarity,39644.0,0.756728,0.247786,0.00000,0.600000,0.800000,1.000000,1.000000
avg_negative_polarity,39644.0,-0.259524,0.127726,-1.00000,-0.328383,-0.253333,-0.186905,0.000000
min_negative_polarity,39644.0,-0.521944,0.290290,-1.00000,-0.700000,-0.500000,-0.300000,0.000000
max_negative_polarity,39644.0,-0.107500,0.095373,-1.00000,-0.125000,-0.100000,-0.050000,0.000000
title_subjectivity,39644.0,0.282353,0.324247,0.00000,0.000000,0.150000,0.500000,1.000000
title_sentiment_polarity,39644.0,0.071425,0.265450,-1.00000,0.000000,0.000000,0.150000,1.000000
abs_title_subjectivity,39644.0,0.341843,0.188791,0.00000,0.166667,0.500000,0.500000,0.500000
abs_title_sentiment_polarity,39644.0,0.156064,0.226294,0.00000,0.000000,0.000000,0.250000,1.000000
shares,39644.0,3395.380184,11626.950749,1.00000,946.000000,1400.000000,2800.000000,843300.000000

In [4]:
# Separar variable objetivo
X = df_clean.drop('shares', axis=1)
y = df_clean['shares']

print("X:", X.shape)
print("y:", y.shape)

X: (39644, 58)
y: (39644,)

In [5]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("Datos escalados:", X_scaled.shape)

Datos escalados: (39644, 58)

esta parte correcto

In [6]:
import pandas as pd

X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

X_scaled_df.describe().T

,count,mean,std,min,25%,50%,75%,max
n_tokens_title,39644.0,4.129479e-16,1.000013,-3.972899,-0.661657,-0.188622,0.757447,5.960828
n_tokens_content,39644.0,7.456003e-17,1.000013,-1.160078,-0.637898,-0.291900,0.359764,16.827550
n_unique_tokens,39644.0,-1.218770e-17,1.000013,-0.155714,-0.021969,-0.002554,0.017179,198.954458
n_non_stop_words,39644.0,-8.065388e-19,1.000013,-0.190487,0.000675,0.000675,0.000675,199.000326
n_non_stop_unique_tokens,39644.0,1.953616e-17,1.000013,-0.211094,-0.019430,0.000398,0.020049,198.883779
num_hrefs,39644.0,8.459696e-17,1.000013,-0.960449,-0.607463,-0.254476,0.275004,25.866534
num_self_hrefs,39644.0,-1.147077e-17,1.000013,-0.854360,-0.594963,-0.076169,0.183228,29.235709
num_imgs,39644.0,-2.007385e-17,1.000013,-0.546872,-0.426526,-0.426526,-0.065486,14.857501
num_videos,39644.0,1.613078e-18,1.000013,-0.304268,-0.304268,-0.304268,-0.060829,21.848691
average_token_length,39644.0,1.376493e-16,1.000013,-5.386389,-0.082705,0.137190,0.363100,4.137038
num_keywords,39644.0,1.376493e-16,1.000013,-3.260042,-0.641015,-0.117210,0.930401,1.454206
data_channel_is_lifestyle,39644.0,-3.728001e-17,1.000013,-0.236445,-0.236445,-0.236445,-0.236445,4.229313
data_channel_is_entertainment,39644.0,0.000000e+00,1.000013,-0.465359,-0.465359,-0.465359,-0.465359,2.148880
data_channel_is_bus,39644.0,-3.441232e-17,1.000013,-0.432948,-0.432948,-0.432948,-0.432948,2.309747
data_channel_is_socmed,39644.0,-1.147077e-17,1.000013,-0.249487,-0.249487,-0.249487,-0.249487,4.008224
data_channel_is_tech,39644.0,6.882464e-17,1.000013,-0.476911,-0.476911,-0.476911,-0.476911,2.096826
data_channel_is_world,39644.0,4.588309e-17,1.000013,-0.519566,-0.519566,-0.519566,-0.519566,1.924682
kw_min_min,39644.0,6.882464e-17,1.000013,-0.389285,-0.389285,-0.389285,-0.317479,5.039228
kw_max_min,39644.0,5.448617e-17,1.000013,-0.299111,-0.183764,-0.128035,-0.039905,77.047823
kw_avg_min,39644.0,-4.588309e-17,1.000013,-0.504799,-0.274845,-0.123824,0.071899,68.487645
kw_min_max,39644.0,-1.147077e-17,1.000013,-0.234755,-0.234755,-0.210611,-0.098514,14.308586
kw_max_max,39644.0,1.835324e-16,1.000013,-3.507348,0.424131,0.424131,0.424131,0.424131
kw_avg_max,39644.0,1.605908e-16,1.000013,-1.919178,-0.639783,-0.108880,0.530702,4.322840
kw_min_avg,39644.0,-5.735387e-17,1.000013,-0.983036,-0.982156,-0.082212,0.826094,2.194303
kw_max_avg,39644.0,-4.875079e-17,1.000013,-0.927595,-0.343528,-0.213406,0.059478,48.000103
kw_avg_avg,39644.0,-3.441232e-17,1.000013,-2.379014,-0.571573,-0.201636,0.352294,30.673519
self_reference_min_shares,39644.0,3.728001e-17,1.000013,-0.202587,-0.170214,-0.141792,-0.070865,42.521194
self_reference_max_shares,39644.0,2.867693e-18,1.000013,-0.251766,-0.224954,-0.183518,-0.056773,20.302961
self_reference_avg_sharess,39644.0,-1.864001e-17,1.000013,-0.264412,-0.223886,-0.173545,-0.049634,34.566824
weekday_is_monday,39644.0,3.638386e-17,1.000013,-0.449391,-0.449391,-0.449391,-0.449391,2.225232
weekday_is_tuesday,39644.0,4.713771e-17,1.000013,-0.478664,-0.478664,-0.478664,-0.478664,2.089150
weekday_is_wednesday,39644.0,5.018463e-17,1.000013,-0.480454,-0.480454,-0.480454,-0.480454,2.081364
weekday_is_thursday,39644.0,2.939386e-17,1.000013,-0.473761,-0.473761,-0.473761,-0.473761,2.110769
weekday_is_friday,39644.0,-3.477078e-17,1.000013,-0.409827,-0.409827,-0.409827,-0.409827,2.440055
weekday_is_saturday,39644.0,-4.373232e-17,1.000013,-0.256821,-0.256821,-0.256821,-0.256821,3.893769
weekday_is_sunday,39644.0,-5.018463e-18,1.000013,-0.272322,-0.272322,-0.272322,-0.272322,3.672121
is_weekend,39644.0,-6.380618e-17,1.000013,-0.388118,-0.388118,-0.388118,-0.388118,2.576536
LDA_00,39644.0,0.000000e+00,1.000013,-0.701974,-0.606714,-0.575012,0.214316,2.823103
LDA_01,39644.0,-3.369540e-17,1.000013,-0.642935,-0.529089,-0.491163,0.043584,3.571575
LDA_02,39644.0,1.720616e-16,1.000013,-0.766711,-0.665444,-0.624924,0.417864,2.494060
LDA_03,39644.0,-1.476862e-16,1.000013,-0.758061,-0.661269,-0.622551,0.514904,2.380742
LDA_04,39644.0,8.603080e-17,1.000013,-0.809287,-0.710477,-0.668449,0.573887,2.396991
global_subjectivity,39644.0,1.835324e-16,1.000013,-3.799778,-0.404544,0.086449,0.556748,4.770438
global_sentiment_polarity,39644.0,0.000000e+00,1.000013,-5.293121,-0.635018,-0.001986,0.603769,6.278089
global_rate_positive_words,39644.0,4.588309e-17,1.000013,-2.273573,-0.644955,-0.034544,0.611328,6.647926
global_rate_negative_words,39644.0,8.603080e-17,1.000013,-1.534231,-0.646191,-0.117726,0.473511,15.545321
rate_positive_words,39644.0,2.064739e-16,1.000013,-3.586415,-0.431906,0.149188,0.619597,1.671100
rate_negative_words,39644.0,8.603080e-17,1.000013,-1.843908,-0.657994,-0.050806,0.619145,4.560030
avg_positive_polarity,39644.0,1.147077e-16,1.000013,-3.384561,-0.455146,0.047161,0.551008,6.181076
min_positive_polarity,39644.0,-1.147077e-17,1.000013,-1.338384,-0.637259,0.063865,0.063865,12.684102
max_positive_polarity,39644.0,-1.777970e-16,1.000013,-3.053998,-0.632520,0.174639,0.981798,0.981798
avg_negative_polarity,39644.0,5.018463e-17,1.000013,-5.797463,-0.539119,0.048470,0.568564,2.031912
min_negative_polarity,39644.0,2.294155e-17,1.000013,-1.646847,-0.613383,0.075594,0.764570,1.798034
max_negative_polarity,39644.0,1.147077e-16,1.000013,-9.358111,-0.183490,0.078642,0.602906,1.127170
title_subjectivity,39644.0,-6.954157e-17,1.000013,-0.870807,-0.870807,-0.408191,0.671245,2.213297
title_sentiment_polarity,39644.0,-1.147077e-17,1.000013,-4.036308,-0.269076,-0.269076,0.296009,3.498156
abs_title_subjectivity,39644.0,-5.520310e-17,1.000013,-1.810719,-0.927896,0.837749,0.837749,0.837749
abs_title_sentiment_polarity,39644.0,5.018463e-17,1.000013,-0.689658,-0.689658,-0.689658,0.415112,3.729424

In [7]:
X_scaled_df.describe().T.round(4)

,count,mean,std,min,25%,50%,75%,max
n_tokens_title,39644.0,0.0,1.0,-3.9729,-0.6617,-0.1886,0.7574,5.9608
n_tokens_content,39644.0,0.0,1.0,-1.1601,-0.6379,-0.2919,0.3598,16.8276
n_unique_tokens,39644.0,-0.0,1.0,-0.1557,-0.0220,-0.0026,0.0172,198.9545
n_non_stop_words,39644.0,-0.0,1.0,-0.1905,0.0007,0.0007,0.0007,199.0003
n_non_stop_unique_tokens,39644.0,0.0,1.0,-0.2111,-0.0194,0.0004,0.0200,198.8838
num_hrefs,39644.0,0.0,1.0,-0.9604,-0.6075,-0.2545,0.2750,25.8665
num_self_hrefs,39644.0,-0.0,1.0,-0.8544,-0.5950,-0.0762,0.1832,29.2357
num_imgs,39644.0,-0.0,1.0,-0.5469,-0.4265,-0.4265,-0.0655,14.8575
num_videos,39644.0,0.0,1.0,-0.3043,-0.3043,-0.3043,-0.0608,21.8487
average_token_length,39644.0,0.0,1.0,-5.3864,-0.0827,0.1372,0.3631,4.1370
num_keywords,39644.0,0.0,1.0,-3.2600,-0.6410,-0.1172,0.9304,1.4542
data_channel_is_lifestyle,39644.0,-0.0,1.0,-0.2364,-0.2364,-0.2364,-0.2364,4.2293
data_channel_is_entertainment,39644.0,0.0,1.0,-0.4654,-0.4654,-0.4654,-0.4654,2.1489
data_channel_is_bus,39644.0,-0.0,1.0,-0.4329,-0.4329,-0.4329,-0.4329,2.3097
data_channel_is_socmed,39644.0,-0.0,1.0,-0.2495,-0.2495,-0.2495,-0.2495,4.0082
data_channel_is_tech,39644.0,0.0,1.0,-0.4769,-0.4769,-0.4769,-0.4769,2.0968
data_channel_is_world,39644.0,0.0,1.0,-0.5196,-0.5196,-0.5196,-0.5196,1.9247
kw_min_min,39644.0,0.0,1.0,-0.3893,-0.3893,-0.3893,-0.3175,5.0392
kw_max_min,39644.0,0.0,1.0,-0.2991,-0.1838,-0.1280,-0.0399,77.0478
kw_avg_min,39644.0,-0.0,1.0,-0.5048,-0.2748,-0.1238,0.0719,68.4876
kw_min_max,39644.0,-0.0,1.0,-0.2348,-0.2348,-0.2106,-0.0985,14.3086
kw_max_max,39644.0,0.0,1.0,-3.5073,0.4241,0.4241,0.4241,0.4241
kw_avg_max,39644.0,0.0,1.0,-1.9192,-0.6398,-0.1089,0.5307,4.3228
kw_min_avg,39644.0,-0.0,1.0,-0.9830,-0.9822,-0.0822,0.8261,2.1943
kw_max_avg,39644.0,-0.0,1.0,-0.9276,-0.3435,-0.2134,0.0595,48.0001
kw_avg_avg,39644.0,-0.0,1.0,-2.3790,-0.5716,-0.2016,0.3523,30.6735
self_reference_min_shares,39644.0,0.0,1.0,-0.2026,-0.1702,-0.1418,-0.0709,42.5212
self_reference_max_shares,39644.0,0.0,1.0,-0.2518,-0.2250,-0.1835,-0.0568,20.3030
self_reference_avg_sharess,39644.0,-0.0,1.0,-0.2644,-0.2239,-0.1735,-0.0496,34.5668
weekday_is_monday,39644.0,0.0,1.0,-0.4494,-0.4494,-0.4494,-0.4494,2.2252
weekday_is_tuesday,39644.0,0.0,1.0,-0.4787,-0.4787,-0.4787,-0.4787,2.0891
weekday_is_wednesday,39644.0,0.0,1.0,-0.4805,-0.4805,-0.4805,-0.4805,2.0814
weekday_is_thursday,39644.0,0.0,1.0,-0.4738,-0.4738,-0.4738,-0.4738,2.1108
weekday_is_friday,39644.0,-0.0,1.0,-0.4098,-0.4098,-0.4098,-0.4098,2.4401
weekday_is_saturday,39644.0,-0.0,1.0,-0.2568,-0.2568,-0.2568,-0.2568,3.8938
weekday_is_sunday,39644.0,-0.0,1.0,-0.2723,-0.2723,-0.2723,-0.2723,3.6721
is_weekend,39644.0,-0.0,1.0,-0.3881,-0.3881,-0.3881,-0.3881,2.5765
LDA_00,39644.0,0.0,1.0,-0.7020,-0.6067,-0.5750,0.2143,2.8231
LDA_01,39644.0,-0.0,1.0,-0.6429,-0.5291,-0.4912,0.0436,3.5716
LDA_02,39644.0,0.0,1.0,-0.7667,-0.6654,-0.6249,0.4179,2.4941
LDA_03,39644.0,-0.0,1.0,-0.7581,-0.6613,-0.6226,0.5149,2.3807
LDA_04,39644.0,0.0,1.0,-0.8093,-0.7105,-0.6684,0.5739,2.3970
global_subjectivity,39644.0,0.0,1.0,-3.7998,-0.4045,0.0864,0.5567,4.7704
global_sentiment_polarity,39644.0,0.0,1.0,-5.2931,-0.6350,-0.0020,0.6038,6.2781
global_rate_positive_words,39644.0,0.0,1.0,-2.2736,-0.6450,-0.0345,0.6113,6.6479
global_rate_negative_words,39644.0,0.0,1.0,-1.5342,-0.6462,-0.1177,0.4735,15.5453
rate_positive_words,39644.0,0.0,1.0,-3.5864,-0.4319,0.1492,0.6196,1.6711
rate_negative_words,39644.0,0.0,1.0,-1.8439,-0.6580,-0.0508,0.6191,4.5600
avg_positive_polarity,39644.0,0.0,1.0,-3.3846,-0.4551,0.0472,0.5510,6.1811
min_positive_polarity,39644.0,-0.0,1.0,-1.3384,-0.6373,0.0639,0.0639,12.6841
max_positive_polarity,39644.0,-0.0,1.0,-3.0540,-0.6325,0.1746,0.9818,0.9818
avg_negative_polarity,39644.0,0.0,1.0,-5.7975,-0.5391,0.0485,0.5686,2.0319
min_negative_polarity,39644.0,0.0,1.0,-1.6468,-0.6134,0.0756,0.7646,1.7980
max_negative_polarity,39644.0,0.0,1.0,-9.3581,-0.1835,0.0786,0.6029,1.1272
title_subjectivity,39644.0,-0.0,1.0,-0.8708,-0.8708,-0.4082,0.6712,2.2133
title_sentiment_polarity,39644.0,-0.0,1.0,-4.0363,-0.2691,-0.2691,0.2960,3.4982
abs_title_subjectivity,39644.0,-0.0,1.0,-1.8107,-0.9279,0.8377,0.8377,0.8377
abs_title_sentiment_polarity,39644.0,0.0,1.0,-0.6897,-0.6897,-0.6897,0.4151,3.7294

PRUEBAAA

In [ ]:
//prueba